version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    ports:
      - "54320:5432"
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "symfony" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  php:
    env_file:
      - ./../../.env
    build:
      context: ../../
      dockerfile: ./examples/docker/php/Dockerfile
      target: 'application'
    depends_on:
      db:
        condition: service_healthy

  nginx:
    build:
      context: ./../../
      dockerfile: ./examples/docker/php/Dockerfile
      target: 'nginx'
    depends_on:
      php:
        condition: service_started
    ports:
      - "8000:8000"
