security:
    providers:
        in_memory:
            memory:
                users:
                    operator:
                        password: '%env(OPERATOR_PASSWORD)%'
                        roles: 'ROLE_USER'
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - App\Security\TokenAuthenticator
            stateless: true
    access_control:
      - { path: ^/api/public, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: '%env(SCHEME)%' }
      - { path: ^/api, roles: ROLE_USER }
