security:
    providers:
        in_memory:
            memory:
                users:
                    operator:
                        password: '%env(OPERATOR_PASSWORD)%'
                        roles: 'ROLE_USER'
    password_hashers:
        Symfony\Component\Security\Core\User\User: plaintext
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            custom_authenticators:
                - App\Security\TokenAuthenticator
            entry_point: App\Security\TokenAuthenticator
            stateless: true
    access_control:
      - { path: ^/api/public, roles: PUBLIC_ACCESS, requires_channel: '%env(SCHEME)%' }
      - { path: ^/api, roles: ROLE_USER }
