imports:
    - { resource: services.yaml }

services:
  _defaults:
      autowire: true # Automatically injects dependencies in your services.
      autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
      bind:
        $stripeClientSecret: "%app.stripe.client_secret%"
        $customFieldCode: "%app.mirakl.stripe_custom_field_code%"
        $redirectOnboarding: "%app.redirect.onboarding%"
        $metadataCommercialOrderId: "%app.workflow.payment_metadata_commercial_order_id%"

  App\Tests\StripeMockedHttpClient:
    class: App\Tests\StripeMockedHttpClient
    public: true

  App\Tests\MiraklMockedHttpClient:
    class: App\Tests\MiraklMockedHttpClient
    public: true

  App\Service\MiraklClient:
    class: App\Service\MiraklClient
    public: true
    arguments:
      $miraklClient: '@App\Tests\MiraklMockedHttpClient'

  App\Service\StripeClient:
    class: App\Service\StripeClient
    public: true
    calls:
      - method: setHttpClient
        arguments:
            - '@App\Tests\StripeMockedHttpClient'
    bind:
      $verifyWebhookSignature: false
