name: build

on:
  push:
  workflow_dispatch:
  pull_request:
  
jobs:
  build:
    strategy:
      matrix:
        php-versions: [8.4]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP, extensions and composer with shivammathur/setup-php
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
        coverage: pcov
      env:
        update: true

      # —— Composer 🧙‍️ —————————————————————————————————————————————————————————

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install -n --prefer-dist --no-scripts

    ## —— Coding standards ✨ ————————————————————————————————————————————————

    - name: Coding standards checks
      run: ./vendor/bin/php-cs-fixer --ansi fix src -vvv --dry-run

    ## —— Static analysis ✨ —————————————————————————————————————————————————
    - name: Static analysis of PHP code (PHPStan)
      run: ./vendor/bin/phpstan analyse src --level=max

    ## —— Tests ✅ ———————————————————————————————————————————————————————————

    - name: Run functionnal and unit tests
      run: ./vendor/bin/phpunit --testdox

    - name: Upload coverage results to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: clover.xml
        fail-on-error: false
